### ISSUE TITLE
p2p/simulations: fix intermittent data races related to Node.Up field

### ISSUE THREAD

**Issue by acud** [ethersphere/swarm#1146]
We should introduce finer granularity locking on individual `Node`s and introduce getters&setters to mitigate ~possible~ data races.

`Node.Up` is not properly encapsulated; sometimes it's accessed under the protection of `Network.lock` sometimes it's just read (e.g., `TestStartStopNode`) directly. => data race

**Comment by frncmx** [comment]
`Node.Up` still causes some data-races. Those are harder to reproduce than in #1110.
=> Let's make the encapsulation.

**Comment by acud** [comment]
@frncmx wasn't this already done?

**Comment by frncmx** [comment]
Nope. I did not touch the PR which aims to resolve this for a while. That is https://github.com/ethereum/go-ethereum/pull/18976

**Comment by acud** [comment]
that PR is fully approved. where's the blocker?

**Comment by frncmx** [comment]
As there is a [suspected deadlock](https://github.com/ethereum/go-ethereum/pull/18976#issuecomment-459411577) somewhere. But that might have been fixed by [p2p/simulations: fix a deadlock calling getRandomNode with lock]( https://github.com/ethersphere/go-ethereum/pull/1208/commits/080f4c26e0bef5c7a7f7c9b70c736167a349a8f4 )

I'm just about to pick this up again to make it to the finish line. Thanks for pinging.

**Comment by frncmx** [comment]
I've split this issue in two.
1) Fix data races by encapsulation of `Node.Up` field => remains this issue
2) Refactor network locking to have a better granularity => moved to https://github.com/ethersphere/go-ethereum/issues/1225

**Comment by acud** [comment]
👍
