### ISSUE TITLE
Create an integration test suite

### ISSUE THREAD

**Issue by holisticode** [ethersphere/swarm#1175]
The `Swarm` code base currently has a set of `longrunning` tests which make no sense to be run as part of the regular unit test suite, as it takes too long to compute.

Many such tests are in fact not of unit test nature, but rather integration tests. They are mostly simulations which need to run in a larger configuration of nodes.

These tests should run in a separate environment and outside the regular `go` test suite. 

Create such an environment and migrate all such tests to this environment.
Candidates for such environments are:
  * Snapshot sync and retrieval tests with `longrunning` flag
  * PSS tests with `longrunning` flag
  * Other large network simulations
  * Swap network simulations with balance check
  * `stream` subscription tests
etc.

**Comment by frncmx** [comment]
Oh; I did not know we have a `longrunning` flag before. So that may make my comment on chat obsolete. Anyway, I said I like [Terraform](https://www.terraform.io/)'s approach of using a different test prefix (i.e., `AccTest`) to separate larger tests (long run time, infra or network needed) from small unit tests (fast, runs without setup).

I'm not sure what the "move" test will mean, but I favor to keep the tests in the Swarm repo. So refactors and seeing what we have remains easier. Maybe we want to have a `_integration_test.go` file suffix for such tests.

Note: we already have some tests separated and scattered in
- https://github.com/ethersphere/helm-charts/tree/master/smoke
- https://github.com/ethersphere/release-staging/tree/master/staging 
- maybe somewhere else, too <= I don't see the big picture.

**Comment by holisticode** [comment]
Duplicate of https://github.com/ethersphere/go-ethereum/issues/1192
