### ISSUE TITLE
Explore migration of a GitHub repository

### ISSUE THREAD

**Issue by adamschmideg** [ethersphere/swarm#1193]
There are discussion around splitting the Swarm code base from Geth. We want to be sure the migration can go smooth and we don't lose issues.

**Try out the following scenario and report results here.**
1. Create a public repository under *https://github.com/ethereum*
2. Fork the repository under *ethersphere*
3. Create some issues under the fork (maybe milestones, something else?)
4. Rename the fork to some unique name what does not collide with anything under *ethereum*
5. Transfer the repo ownership from *ethersphere* to *ethereum* in the settings menu

Did we lose anything? Do we still have the issues after the migration?

*Note:* you might do the above with *ethersphere* and your own private account, if you don't have permissions to create a repo under *ethereum*

**Comment by nonsense** [comment]
Done at:
1. https://github.com/powpark/test-project - the original project
2. https://github.com/powpark/test-project forked to https://github.com/nonsense/test-project
3. https://github.com/nonsense/test-project renamed to https://github.com/nonsense/test-project-alternative
4. Fork status removed at https://github.com/nonsense/test-project-alternative
5. https://github.com/nonsense/test-project-alternative migrated to https://github.com/powpark/test-project-alternative-fork-status-removed

Links to Issues, PRs, Wiki pages automatically fixed by Github with proper redirects.
