### ISSUE TITLE
Add support for `global-store` in our helm charts

### ISSUE THREAD

**Issue by nonsense** [ethersphere/swarm#1202]
@janos merged the `global-store` command and support for its API in `swarm`.

We should update our helm charts, so that we can configure a `swarm-private` deployment to use the global store.

`swarm` chart should not be changed - I don't think we should ever use the `global-store` API with the public network, at least I can't think of a reasonable use-case right now.

**Comment by skylenet** [comment]
Changed our Dockerfile so that we have separate images for `swarm`, `swarm-smoke` and the new `global-store` : https://github.com/ethereum/go-ethereum/pull/19038 

Afterwards I'll update Buddy.Works to automatically push the `edge` tags on merge to master (ethersphere/go-ethereum) for all images. 

These will be available in here: 
https://hub.docker.com/r/ethdevops/swarm/
https://hub.docker.com/r/ethdevops/swarm-smoke/
https://hub.docker.com/r/ethdevops/swarm-global-store

**Comment by skylenet** [comment]
Added a new private cluster to staging that uses the global-store: https://github.com/ethersphere/release-staging/pull/27
