### ISSUE TITLE
Bug when hashing a file: Returned hash count is not always the same

### ISSUE THREAD

**Issue by holisticode** [ethersphere/swarm#1211]
This problem appeared while working on https://github.com/ethersphere/go-ethereum/pull/1185.

To reproduce it, one can run the `TestGetAllReferences`  in `swarm/storage/filestore_test.go`, which is currently disabled on `master` due to this bug.

Running that test, the result is sometimes 247, sometimes 248 (which apparently should be the correct number), and sometimes **even 246** for splitting a 1000000 bytes file.

This seems like a major bug and should be addressed soon.

**Comment by nolash** [comment]
The problem is a concurrency issue in your `HashExplorer`. If you add a mutex and lock the write to the `HashExplorer.References` array, the test passes every time.

It's hard to tell, but perhaps you also ideally should also call `HasherStore.Wait()` before you count the `References` in `FileStore.GetAllReferences`.

**Comment by holisticode** [comment]
Closed by https://github.com/ethereum/go-ethereum/pull/19028
