### ISSUE TITLE
snapshot binary cannot generate 2 nodes snapshot

### ISSUE THREAD

**Issue by holisticode** [ethersphere/swarm#1241]
```
$ swarm-snapshot create -nodes=2 -services="bzz,pss" snapshot_2.json 
ERROR[02-19|21:02:56.105|swarm-snapshot/main.go:35] connect nodes: connection between 2170a0986666e37ce50a3102c0582c047af1a2d3588c9f99cc3de954d2825460 and 2293cef6feaf578d2767f482575aad9e0672b402dec60f46f6fba219342533fd recently attempted 
```

All other currently used node counts work fine, only the 2 nodes snapshot fails.
It should be of course questioned if there is any merit in having a 2 nodes snapshot at all; the decision may affect `swarm/pss` tests though

**Comment by aperonam** [comment]
@holisticode I've noticed that this is due to  connectNodesRing making  two connections between the nodes (A-B-A), this will fail when doing the second connection (B-A) as the nodes have already connected recently (A-B). 
Adding a check in createSnapshot to check if only 2 nodes requested, and in that case use connectNodesChain instead of connectNodesRing, fixes it. 

Should I go ahead and make a PR?

**Comment by holisticode** [comment]
@aperonam I would very much appreciate! Thank you
