### ISSUE TITLE
Flaky pss TestCache test with race detector enabled

### ISSUE THREAD

**Issue by janos** [ethersphere/swarm#1256]
How to reproduce:

```
go test -v -count 1 -race github.com/ethereum/go-ethereum/swarm...
```

```
=== RUN   TestCache
--- FAIL: TestCache (11.02s)
    pss_test.go:250: unexpired message should be in the cache: [178 119 88 53 3 5 212 153 44 64 8 203 144 70 163 43 51 100 253 228 13 13 158 100 100 240 146 26 227 67 208 223]
```

**Comment by aperonam** [comment]
I have been taking a look at this and it seems that  is caused by the pss hashPool having BMT hashers and SHA3 hashers. If the digest that is calculated at the begining of the test `digestthree := ps.msgDigest(msgthree)` uses a different hasher type than the digest made later when adding to fwdCache ` ps.addFwdCache(msgthree)`, then the hash will be diferent and when checking ` _, ok := ps.fwdCache[digestthree]` appear  as if the message is not in the cache.

Is there a reason why the hashPool has two types of hashers?

**Comment by janos** [comment]
This test no longer exists.
