### ISSUE TITLE
bzz-hash should not fail on root chunk missing

### ISSUE THREAD

**Issue by acud** [ethersphere/swarm#1401]
as reported by @homotopycolimit, swarm returns a `404` for a `bzz-hash` request for a hash that doesn't exist. it should just resolve the ENS entry and return the hash

**Comment by cobordism** [comment]
actually, I'm not even sure that 404 ever surfaced.

When I called bzz-hash on an ENS name that had a content hash registered, but whose content was not available in swarm, the browser was just stuck in a loop.

Here is when I made the request:

INFO [05-19|00:18:03.419] created ruid for request                 ruid=a9aedc25 method=GET url=/
INFO [05-19|00:18:03.419] respondHTML                              ruid=a9aedc25 code=200
INFO [05-19|00:18:03.419] request served                           ruid=a9aedc25 code=200 time=156.017µs
INFO [05-19|00:18:18.795] created ruid for request                 ruid=0a2aafaa method=GET url=/bzz-hash:/videos.theswarm.eth
INFO [05-19|00:18:18.795] setting request host                     ruid=0a2aafaa host=localhost:8500

and then, minutes later, only when I closed the tab did I get the following

INFO [05-19|00:21:14.236] respondError                             ruid=0a2aafaa uri=bzz-hash:/videos.theswarm.eth/          code=404 msg="root chunk not found a5714657533ec0f7185e2e2626ec86431d17dba3c0cb4f222773e44624364deb: context canceled"
INFO [05-19|00:21:14.236] respondHTML                              ruid=0a2aafaa code=404
ERROR[05-19|00:21:14.236] write tcp 127.0.0.1:8500->127.0.0.1:54376: write: broken pipe 
INFO [05-19|00:21:14.236] request served                           ruid=0a2aafaa code=404 time=2m55.441623453s


and when I use bzz:// instead of bzz-hash:// I also do not get a 404, but the browser is just stuck in a loading loop with nothing happening.  Shouldn't the attempted retrieval of the root chunk time out and let the browser know of either a timeout or a 404?


Edit: in the latter case, I get
code=404 msg="Manifest not Found"
in the swarm console after I close the tab, but nothing while I leave it open.

**Comment by acud** [comment]
Both are the same case. As we’ve previously mentioned a 404 in swarm essentially equals a timeout. We don’t have a notion of something not being found because it’s not there, but rather we have a notion of something not found because we could not fetch it within the timeout.

What you’ve described above is essentially the same issue manifesting in different ways

**Comment by cobordism** [comment]
essentially a timeout? well then let's have an actual timeout.

right now we're getting neither a 404 nor a timeout response in the browser. It just hangs forever.
