### ISSUE TITLE
User can pay gateway fee

### ISSUE THREAD

**Issue by holisticode** [ethersphere/swarm#1438]
This issue is part of the https://github.com/ethersphere/user-stories/issues/23 user story.

A public gateway should be able to show a user how much the retrieval of a file would cost. A user should be able to pay the fee due.

This issue is about implementing the fee payment.

@zelig @homotopycolimit @nagydani please specify the requirements for the implementation of this issue.

**Comment by cobordism** [comment]
A public gateway can only show a price per kilobyte for retrieving content but cannot give an absolute price because the total size is not known ahead of time. 
See also https://github.com/ethersphere/swarm/issues/1437

a node can show how expensive retrieving any given file would be.
a node cannot show how expensive retrieving any given dapp/homepage would be.
