### ISSUE TITLE
Command-line tool to query balance with a peer

### ISSUE THREAD

**Issue by holisticode** [ethersphere/swarm#1447]
Currently there should be an RPC endpoint implemented which allows to query the node for a balance with a peer.

Validate that this endpoint still exists (there has been a radical simplification of the code where this may have fallen pray to removal).

Then write a command-line tool to query a balance with a peer.

Evaluate if a command-line tool is the best approach. Possibly interview stakeholders (node operators?). Goal is to provide relevant information to node operators.

**Comment by mortelli** [comment]
Moving back to **In Progress** because the current `GetAllBalances` implementation only returns balances in memory, which is a subset of the balances on disk.

**Comment by mortelli** [comment]
Also: the current implementation is under the `bzz` API, instead of `accounting`. See related issue #1591.

**Comment by mortelli** [comment]
Since #1591 isn't done yet, I've temporarily placed the new functions under a `swap` API. This should be revised once said issue is done.

The calls to query balance are:
- `swap_balance` with an `enode.ID` string as it's first and only argument (e.g. `"3d4b32546191419cf1229036bca03c987e49d17027bf7f2fba0691b6ef171b60"`).
- `swap_balances` for a complete list of _all_ stored and in-memory balances.

Even though the methods now include data from disk, they do not copy this data to memory after fetching it.
