### ISSUE TITLE
Keeping track of cumulative balance 

### ISSUE THREAD

**Issue by Eknir** [ethersphere/swarm#1551]
In the go implementation of Swap, we keep track of the net balance, meaning that we reset the balance to zero every time we send/receive a cheque. 

In the smart contract, we only increase the balance and increase a paidOut parameter every time we cash out. 

There is one thing wrong with this implementation, and one thing is a possible improvement.
What is wrong is that we naively set the balance to zero every time, without checking the amount on the cheque. This can allow a node to naively believe a cheque was issued for a certain amount, whereas the amount on the cheque could have been lower.
What can be improved is that we keep track on the go side of a cumulative unreceived balance (for total SWAP balance outstanding) and a cumulative received balance (equal to the cumulative value in the smart-contract). If the difference between the two is higher than the payment threshold, we should request a cheque and if we receive this cheque, we set the cumulative received balance to the value on the cheque.

**Comment by vojtechsimetka** [comment]
Balance should be a cumulative value and compared as such. So in practice current balance would be retrieved as such:

`balance = balanceCummulative - lastChequeAmount/pricePerByte`

and the trigger for cheque request

`balance >= treshHold`

So this function should not exist.

**Comment by vojtechsimetka** [comment]
@holisticode sorry I missed it in the meeting, why did we close this? I could not find it anywhere.

In general, could we maybe write at least one line of justification for issues that are closed without being implemented?

**Comment by holisticode** [comment]
During the meeting it became clear that as the cumulative balance of the swarm node is kept in `honey`,  the contracts keep them in `wei`. Someone had said that on Balaton, it had been argued that the primary objective of maintaining a cumulative balance in the node was to keep it in sync with the SC, which had become moot by now.

I specifically did ask the team during the meeting if anyone thought that we should still keep it cumulative, but nobody defended the position, which is why I closed the ticket.

I also specifically made clear that it can be re-opened if it was deemed that it should be.

Keep in mind though that maintaining the balance cumulative means that we would have to somehow also store the last position, otherwise how can we compare with the thresholds?

> In general, could we maybe write at least one line of justification for issues that are closed without being implemented?

Absolutely, sorry for that.
