### ISSUE TITLE
Integrate smart contract and go code repos

### ISSUE THREAD

**Issue by holisticode** [ethersphere/swarm#1618]
There is currently an independent repo for smart contracts and the go code.

This implies that the go bindings are currently manually generated from the smart contract repo and pasted into the go repo.

This should be an automatic process.
It seems like the best approach to move the smart contracts into the go code repo.

Related issue:
https://github.com/ethersphere/swarm/issues/1442

**Comment by vojtechsimetka** [comment]
While I agree that should be the goal I would like for @Eknir & @ralph-pichler to write the problems with automated binding generation and consequent verification of deployed contract code, so that we have full picture.

**Comment by Eknir** [comment]
Automatically generating new go-bindings can create problems when the new version of the smart-contracts is incompatible with the old version. Imagine the proposed simplification of the smart-contracts where we will get rid of waivers: if we would automatically generate new go-bindings for this update to the smart-contracts, we might run into big-troubles as some calls (e.g. submitCheque) will be non-existent anymore while others (e.g. cashCheque) now have a different function signature.

As the smart-contract evolves, it might happen that we will eventually have to deal with multiple chequebook implementations living next to each other. Last week, Aron and I have been discussing a generalization of payment modules and I think that a different version of a chequebook would be a different payment module. 

With regards to verification of code: @ralph-pichler has proposed to implement a factory pattern (smart-contract which deploys other smart-contracts). Verification then means that the go-code will do a call to the factory, mentioning a smart-contract address, and the factory will respond whether this address is a contract which he deployed.

**Comment by holisticode** [comment]
> Automatically generating new go-bindings can create problems when the new version of the smart-contracts is incompatible with the old version. Imagine the proposed simplification of the smart-contracts where we will get rid of waivers: if we would automatically generate new go-bindings for this update to the smart-contracts, we might run into big-troubles as some calls (e.g. submitCheque) will be non-existent anymore while others (e.g. cashCheque) now have a different function signature.

I don't think this is the way this should be handled. If something on the smart contract changes, then it needs not only change the go-bindings, but also the code which calls it. It is an "atomic" change so to speak and should be addressed in the same workflow.

The multiple chequebook implementation is not an argument against a unification IMHO. If multiple chequebooks are live at the same time, it responds to a real need and thus the go code should be able to call both as well (otherwise what's the point of having multiple). If they are not live at the same time it probably is some experimental feature which can be addressed with branches or configuration. Otherwise, please explain why it affects the repo unification.

I fail as well to understand why the factory pattern affects this issue.

**Comment by holisticode** [comment]
I think this should be discussed in the wider team, as it is not a incentives-track internal issue only. I think it should be discussed at the next roundtable https://hackmd.io/oj9_cT2KQimMdIPe_W_ejQ

**Comment by ralph-pichler** [comment]
I see multiple issues with moving the source code of the contracts into the swarm repo and/or trying to automate the binding generation.

For once the contracts are set up as a truffle project (for ease of testability) which requires a very specific directory structure. While this is probably possible this will introduce both Solidity and JavaScript into a codebase that would otherwise be go only without providing much benefit. Since the contracts also reuse code from `openzeppelin-solidity` we would have to do an `npm install` to get all the source code (or copy the openzeppelin code which is even worse imo). Therefore swarm would get a dependency on at least `nodejs`.

At some point there will probably be multiple live deployments of different Swap contracts. Since we still need to support interaction with older versions we would have to copy the solidity files every time we make a change so we still have the old one for generating the bindings. If it is a separate repository we could simply checkout that repo as a submodule at different commits.

For bytecode verification to work we need to ensure that `Swap` is compiled with a very specific version of the Solidity compiler. Once there are multiple contracts which have been compiled with different solc versions autogenerating those bindings might involve downloading multiple different solc binaries. The only reasonable way to do this is using the `ethereum/solc-bin` repo which would also add a dependency on `nodejs` (the alternative is to manually compile solc which is a non-trivial c++ project). However autogenerating the bindings also involves the use of the `abigen` tool from `go-ethereum`. Not every version of `abigen` seems to be compatible with every version of `solc` (as we learned when we tried to generated bindings at Balaton). This means that over time we might need different versions of `abigen` to autogenerate everything correctly and deterministically. Since there is no repo of precompiled `abigen` binaries, this means we would probably have to compile multiple versions of `go-ethereum` during autogeneration.

Another potential issue is that on the long term this probably won't remain the only swarm client. If the contracts are in this repository this means that other clients either have to manually copy the contract source code into theirs or pull the entire `ethersphere/swarm` repo as a submodule (and therefore a complex go codebase they otherwise wouldn't need).

My recommendation would be to not automate this and keep contracts in a separate repository. Instead we should continue to generate them manually and instead add documentation as to how and with which versions the bindings were generated.

**Comment by holisticode** [comment]
As of roundtable of 30th July 2019, the decision was made that indeed a merge of the repos would **not** make sense, but that there should be some automation in place. Conceptually it should work like usual go-vendoring works.

@ralph-pichler please outline in a comment how the solution will be, thanks

**Comment by ralph-pichler** [comment]
There will have to be a separate repository for the go bindings which will be a regular go library (with `mod.go` and everything necessary) so that it can be vendored or be used as a go module like any other go repo.

The open questions are how to structure this library and how and when newer bindings go into it.

We need for every version of the `Swap` contract that at any point was in production:
- the bindings generated by `abigen`
- the deployed bytecode binary (which is not part of `abigen`, instead the go file is generated by a `node.js` script in the sw3 repo)

The bindings should (at least for the most part) always be backwards compatible with older versions of the contract. But the bytecode may change even if the source code stays the same (e.g. compiler upgrade after a security issue with `solc`). Therefore we can never update the bytecode in that repo, instead we have to add the new one (otherwise we could not verify the bytecode of older swap contracts).

One approach would be to have the structure similar to what is now in the `contracts/swap` directory: `swap.go` which provides a common `Contract` interface regardless of which version is really used and then there would be (potentially) multiple versions of what is now the `contract` folder. `swap.go` could then detect the version based on the bytecode and give you the "right" binding.

A probably better alternative would be to leave all this complexity of detecting and abstracting versions in the swarm repo itself. Instead we just put the raw bindings (and deployed binary) into the library. Then the structure would be something like (I used here `version1` (could also be the commit hash) instead of `v1` to make clear that this is not go module versioning):
- `go.mod`
- `version1/simpleswap/simpleswap.go`
- `version1/simpleswap/code.go`
- `version2/simpleswap/simpleswap.go`
- `version2/simpleswap/code.go`
- ...

Using go modules there could also be multiple versions of the same library in the same repo. But then we would mix versions of the go library with versions of the smart contracts:
- `v1/go.mod`
- `v1/simpleswap/simpleswap.go`
- `v1/simpleswap/code.go`
- `v2/go.mod`
- `v2/simpleswap/simpleswap.go`
- `v2/simpleswap/code.go`
- ...

In that case different versions should be able to be imported on the `swarm` side using `import “github.com/ethersphere/sw3-go/v1”` etc. But after playing around a bit with go modules this seems to have a lot of disadvantages here (such as having to use a v1* tag if we needed to adjust the bindings for the oldest version for some reason). Note that simply updating the go files in the repo and then trying to import different versions from `swarm` won't work because go won't allow multiple versions with the same path.

Another question is when and how to generate bindings and add them to the repo. Since it doesn't make sense to generate bindings if only `README.md` has changed I would suggest that bindings are only generated if a tag is created (which we would do on every proper release of new contracts). On every tag we run then (in the CI):
- run the tests
- clone the bindings repo
- add the generated files to the repo
- commit and push

**Comment by ralph-pichler** [comment]
After more experimentation I came up with this simpler solution without any `go.mod` files.

* `contracts-v0-1-0/simpleswap/simpleswap.go`
* `contracts-v0-1-0/simpleswap/code.go`
* `contracts-v0-2-0/simpleswap/simpleswap.go`
* `contracts-v0-2-0/simpleswap/code.go`
where `simpleswap.go` is the generated binding and `code.go` contains the deployed bytecode.

On the swarm repo side we import the right directory for whatever swap version we want to use
```go
import "github.com/ethersphere/sw3-go/contracts-v0-2-0/simpleswap"
```

If we need to support multiple versions of the swap contract we can just import multiple under different aliases:
```go
import (
  simpleswapv2 "github.com/ethersphere/sw3-go/contracts-v0-2-0/simpleswap"
  "github.com/ethersphere/sw3-go/contracts-v0-3-0/simpleswap"
)
```

When we use this in swarm it will use the same version of `go-ethereum` dependencies as swarm. If we need to lock a binding to a specific version (e.g. if `go-ethereum/accounts/abi/bind ` breaks compatibility) we can manually add a `go.mod` later and then update the vendored dependency.

New versions are automatically added to the go repo on every `v*.*.*` tag iff all the tests and linting passed. Once a binding has been generated the CI won't touch it again (unless the tag is recreated). Therefore if we need to fix something in a binding for a specific version later we can just manually do that.

A demo repo that was created that way can be found here: https://github.com/ralph-pichler/sw3-go/. This was generated with the CI config from here: https://github.com/ralph-pichler/swap-swear-and-swindle/blob/master/.travis.yml

**Comment by ralph-pichler** [comment]
Integrated in #1683
