### ISSUE TITLE
swarm node doesn't reconnect to peers correctly after restart

### ISSUE THREAD

**Issue by nonsense** [ethersphere/swarm#1730]
After a node established peers when it joins the network, if it is restarted, for some reason it doesn't correctly re-establish connections with known peers.

It is not clear why this is happening, and definitely not due to the `maxpeers` setting, as peers have much fewer peers than their `maxpeers` limit.

<img width="1031" alt="Screenshot 2019-09-05 at 17 08 07" src="https://user-images.githubusercontent.com/50459/64349839-4f44d800-d000-11e9-92e1-3748c016465d.png">

In screenshot, at the top we see a node's connectivity when it is first started and it has established connections to its peers.

In the bottom screen we see its connectivity after reboot - it fails to connect with some of its closest peers.

**Comment by nonsense** [comment]
According to git bisect, the first bad commit is `fe77fee5fa13973a972b891b952f1632ddd3aac0`

**Comment by janos** [comment]
I can confirm that reverting fe77fee5fa13973a972b891b952f1632ddd3aac0 fixes the issue.

**Comment by jmozah** [comment]
@nonsense what does the log say... Any Errors during reconnect?

**Comment by zelig** [comment]
@jmozah @nonsense thanks for finding this.
I think this is completely wrong logic here; 

https://github.com/ethersphere/swarm/blob/master/bzzeth/bzzeth.go#L114

the bzzeth protocol between two swram nodes is idling until the whole service quits on the node. 
Therefore the peers cannot really quit the protocol, after they disconnect. Instead of b.quit the peers quit channel should be used on this line
https://github.com/ethersphere/swarm/blob/master/bzzeth/bzzeth.go#L67

b.quit should  be used for service specific forever loops if any.

**Comment by acud** [comment]
:+1: sounds like the correct solution

**Comment by acud** [comment]
oops. it's not that trivial. i just tried to implement this. using this current design, adding a `quit` channel does not solve the problem, because the read from the channel just sends the goroutine into a deadlock and even the `add` and `defer remove` statements will not execute and even on peer disconnect there's not going to be any actual removal of the peer because the goroutine is deadlocked and the `Run` function did not return

**Comment by jmozah** [comment]
https://github.com/ethersphere/swarm/pull/1745
