### ISSUE TITLE
Remove failed request from memstore

### ISSUE THREAD

**Issue by gbalint** [ethersphere/swarm#264]
After the request fails it should be removed from the @memstore

**Comment by nonsense** [comment]
We have a few different approaches to solve this:

1. Understand how to remove chunks from the memstore, and remove the chunk / chunk request if the request fails.

~2. Do not put the chunk requests in the memstore in the first place, but only after they are successful, and we have a real chunk for the memstore. (I guess this is not a good idea, as we would have to check both the memstore and the "inflight requests" store, which defeats the purpose)~

3. Have a flag as part of the chunk request to signal if a chunk request is in flight, or if it has failed. This would mean that the memstore will have garbage chunk requests that have failed, and we must periodically remove them.

I am not sure which one is the best, I am investigating how exactly memstore is working, so that I see which one of these is feasible.

@zelig @gbalint any feedback is welcome :)

**Comment by gbalint** [comment]
In case of 2. you have to store it somewhere anyway before it is retrieved, otherwise another Get for the same chunk would result in initiating another request.
1. is definitely good solution, i don't know how hard it is
3. would mean we need some kind of garbage collection, but that is probably not easier than 2....

So I think 1 would be the proper solution. If it is too hard let's think more about it.

**Comment by zelig** [comment]
fixed  in https://github.com/ethersphere/go-ethereum/commit/a3c93ca4c46cb8b63afd8fc22619d4a0c43d49cf
