### ISSUE TITLE
Make it possible to change the root chunk of a mutable resource

### ISSUE THREAD

**Issue by nolash** [ethersphere/swarm#418]
Currently, upon creating a new mutable resource, the root chunk describing the required metadata for the resource is pointed to by the ens namehash of the resource (ens) name. For this reason it is not possible to change the update frequency after the resource has been created.

This constraint should be removed.

See also https://github.com/ethersphere/go-ethereum/wiki/Resource-update---ideas-and-analysis

**Comment by jpeletier** [comment]
This is what I would do that builds on top of what we already have. Sounds funny, but I am serious! :

Register in ENS a mutable resource A with the expected frequency with which you would like to change frequency.

Use mutable resource A to point to the root of a second, disposable, mutable resource B with a different frequency.

If you need to change frequency, simply create a new resource C and have A point to it.

Since A has been created with the expected frequency with which you would change the frequency, it should not be a lot of extra hops, unless you did not predict correctly how often you wanted to change frequency 😂. If so, insert another level of indirection which will allow you to periodically change the frequency with which you change frequency! 

There, I said it.

**Comment by nolash** [comment]
But how do you know beforehand how often you would change frequency @jpeletier ?

**Comment by jpeletier** [comment]
There are so many things that I would like to know beforehand... ;)

My guess is that the frequency of the frequency would be much bigger than the frequency, so make a guess and then recalibrate. Worst case you'll be stacking versions on top of period points.

Each level of MRU pointing to another MRU is like a derivative function. Eventually you'll reach zero.

**Comment by nolash** [comment]
> point to the root of a second, disposable, mutable resource B with a different frequency.

what is the "different frequency"?

> If you need to change frequency, simply create a new resource C and have A point to it.

What about the existing updates in B?

**Comment by jpeletier** [comment]
> what is the "different frequency"?

That different frequency would be the one that you would like to switch to from that point on.

So, back to the example before, to try to rephrase it for everyone else. Let's say you start a project where you expect to update the world **every day** on some subject, but you are not sure if you will have to **switch to weekly updates** after the first 5 days. To cover this:

1.- you register resource A in ENS with for example a frequency of 1 month.
2.- you create a resource B with frequency 1 day and store its `rootAddr` in A's first  update as a multihash. So B's `rootAddr` falls in A's period 1, version 1 update (Ap1v1)
3.- you publish the first daily update in B, and do so promptly every day after.

At this point, looking up the content in B takes three hops: lookup Ap1v1 -> B -> data

However, after the 5 days an event happens and you have to switch to weekly updates. How?

1.- Register new resource C with weekly frequency.
2.- Update A to point to C instead of B. Doing this creates a second version on the first period of A (Ap1v2), since we are still within the first month

At this point, looking up the content takes four hops: Ap1v1-> Ap1v2 -> C -> data, but you didn't have to update ENS.

> What about the existing updates in B?

The interesting bit comes with the next enhancement I think we need for MRUs, which is to store the `updateAddr` (update chunk key) of the previous update in an update chunk, thus creating some sort of blockchain of updates of a given resource that allows you (1) to trace the history back and (2) prove that you are not rewriting your resource update history. So this sort of feature would allow you start pulling the string and get all updates in the past.

I am working on a POC of this, I hope to have something by next week.

**Comment by zelig** [comment]
@jpeletier I dont think this extra level of complexity is needed. To know that you want to change the frequency is already a strong assumption, knowing when you want to do it is not realistic.
How about you just change the ENS entry then? i think we can afford updating an ENS entry every time we want to change the frequency

My view on this is that the scheme is already really powerful. In fact if you register MRU metadata with ENS, nodes that use MRUs already gain a lot more independence: due to the rare nature of ENS updates, nodes could get away with caching ENS entries. 

To support the notion that one MRU metadata chunk is an update of another one, we could indeed introduce another MRU level, but is the complexity really needed?

I think it is more realistic to always have a new estimate for the next version as part of the update. Those guys that get notified or poll to stay uptodate could always have the most uptodate info on when to expect the next one. (imagine a database aggregator, for which frequency. of updates is not a function of their choice but the result of the update frequency of its primary sources. )

**Comment by jpeletier** [comment]
@zelig I was just toying with ideas of what MRUs could accomplish. You're right that users should afford to change the frequency with ENS if they made a mistake.

I note the idea of including a new estimate in each update. With the last refactor in #704, the code is ready to add these kind of improvements without having to make a mess. I hope we can merge it soon so others can build on as well.

Thanks!
