### ISSUE TITLE
mutable resources vz bzz-raw and bzz-hash

### ISSUE THREAD

**Issue by cobordism** [ethersphere/swarm#525]
Mutable resources don't work well with bzz-hash and bzz-raw.

For example I expect bzz-hash://mutable.eth/3/ to give me the hash of the content served are bzz://mutable.eth/3/

Similarly, bzz-raw://mutable.eth/3/ does not give me the content.

Raw and Hash assume standard manifests. They should be made compatible with mutable resources.

**Comment by cobordism** [comment]
what is our policy if a manifest has a mutable resource as default entry (and this resource has an update /3) and the manifest also has an entry for /3?

Would it be beneficial to use fragments rather then /suffixes for mru versions?

**Comment by nolash** [comment]
I think `bzz-raw` shouldn't be used here. Getting raw resource updates should be handled through `bzz-resource`.

**Comment by nolash** [comment]
I've been playing around with this today a bit, and I'm not sure how we should approach it.

When you create a mutable resource, a manifest is created. This manifest is of a special type. Currently its pointer points to the resource update root chunk, which is a special data chunk consisting of `startblock|frequency`.

If you try to read this block with `bzz` or `bzz-raw` it will fail (the interpretation of the chunk length field will be bogus, for one thing). Bad things will also happen if you point `bzz` or `bzz-raw` requests directly to update data chunks, since they don't follow normal swarm data chunk format either.

In fact, the only usable interface to resource updates using the normal schemes is using `bzz` with the _manifest_ hash generated by the initial resource creation.

Returning that hash is not really entirely correct either, since `bzz-hash` really is used for getting the individual chunk data hashes for individual paths below a manifest. Resource updates don't really have this. It has versioning instead, but these, as said point to the data chunks that can't be read with normal schemes.

**It seems to me that we should just not support resource updates with these schemes.** How about if we add a `400 Bad Request` return value on attempts to use them with resource update manifests. For other uses (for example a resource update chunk directly) we can't even really tell if it's a resource update related chunk or not.

**Comment by acud** [comment]
> Returning that hash is not really entirely correct either, since bzz-hash really is used for getting the individual chunk data hashes for individual paths below a manifest. Resource updates don't really have this. It has versioning instead, but these, as said point to the data chunks that can't be read with normal schemes.

The resource updates point to a manifest eventually - why can't we resolve the `bzz-hash` request to point to the correct manifest hash?

I think that both schemes should work, or at least `bzz-hash`. 
And if we can't implement cross-scheme compatibility on our own platform and our own data types - this means we have a design issue.

On a side-note I'll mention that I really don't like the fact that the versioning goes into the locator. It should sit in a header. If someone wants to go through the hassle of going through past versions they can be lured into putting it in a specific header `X-Swarm-Bzz-Resource-Version`. The fact that the version is in the locator disrupts even more the model that we use to match paths in a manifest and is not really clear to me how it will behave as of such.

**Comment by cobordism** [comment]
> On a side-note I'll mention that I really don't like the fact that the versioning goes into the locator. It should sit in a header. 

I'm inclined to agree on that point.

**Comment by nolash** [comment]
> On a side-note I'll mention that I really don't like the fact that the versioning goes into the locator.

Noted but please let's leave that for a separate discussion.

-----

Let's take a look at how everything works after the root chunk refactor:

### `POST bzz-resource://foo.eth[/raw]/13`

**What it does**

Create a new resource for `foo.eth` from current start block with frequency 13.

**How it does it**

* If `/raw` is first path element, treat the data as raw data. Otherwise treat the posted data as multihash.
* Creates the resource
* Creates a "mutable resource type" manifest which hash points to the root chunk
* Returns the key to the manifest.

### `POST  bzz-resource://foo.eth[/raw]`

**What it does**

Adds a new update to the mutable resource.

**How it does it**

* If `/raw` is first path element, treat the posted data as raw data. Otherwise treat the posted data as multihash.
* Resolves `foo.eth` and retrieves the "mutable resource type" manifest at that location
* Interprets the `Hash` of the manifest as the key of the resource root chunk
* The period and version will be automatically calculated from the resource history and the current block height.

### `GET bzz-resource:/foo.eth[/period[/version]]`

**What it does**

Returns the contents of the current update to the mutable resource.

**How it does it**

* Resolves `foo.eth` and retrieves the manifest at that location
* Interprets the `Hash` of the manifest as the key of the resource root chunk
* Asks the backend to load the resource at the resource root chunk key
* Asks the backend to get the specified update of the resource (if period and/or version is specified, will get that specific update)
* Returns the actual update data as `application/octet-stream`

### `GET bzz:/foo.eth`

**What it does**

Retrieves the latest update of `foo.eth`.

**How it does it**

* Resolves `foo.eth` and retrieves the manifest at that location
* Checks if the content type of the manifest is the *mutable resource type*. If not, defer to normal operations, or else:
* Check if the resource update is multihash type. If not, set returned `LazySectionReader` to be a bytereader for the resource update's data field, or else:
* Retrieve the manifest pointed to by the multihash, and set the manifest entry to be the root path of that manifest.
* Serve that entry as if it was the entry directly asked for through `bzz://`

-----

Then, as far as I understand, the remaining schemes should do the following?

### `GET bzz-hash:/foo.eth`

**What it does**

Returns the key to the "mutable resource type" manifest. This will give the same result as the ENS lookup.

### `GET bzz-raw:/foo.eth`

**What it does**

Returns the "mutable resource type" manifest itself in `text/plain` Content-type.

-----

In the above, no schemes give direct access to the mutable resources root chunk key, *except* the `bzz-raw` retrieval of the "mutable resource type" manifest, which will list it in its `Hash` member.

This means that all resource update operations through `http` will take the extra step of resolving the resource update through a manifest, with the resulting performance hit. I'm not sure if I like this, really.

**Comment by zelig** [comment]
@homotopycolimit @jpeletier close?
