### ISSUE TITLE
Update Mutable Resource Update off-chain estimation 

### ISSUE THREAD

**Issue by nolash** [ethersphere/swarm#528]
When not connected to the blockchain, mutable resource updates will resort to heuristics to determine what the current blockheight is. This approximation is currently fixed to the average of a concrete block sample divided by the epoch block (see the struct `BlockEstimator` in `swarm/storage/resource.go`). The initial average has a hardcoded tolerance so that if the resource is created without connection to the blockchain, the estimated start block should be higher than the actual block height. If not, then the historic lookup when on-chain will start before the start block, and the update will not be found.

However, if one later reverts to heuristics, updates made while on-chain will risk being lost, if the difference between estimation and actual blockheight is too large.

Also, of course, over time, the sample hardcoded in the code will cause a certain amout of drift, if the average block time will have changed since the time of the sample.

To limit this drift, when going on-chain, both at stop and start of node, the block height should be sampled again, and the state stored in config, so that subsequent estimation will use this updated sample.

**Comment by jpeletier** [comment]
In my PR #704 this situation is resolved by using the system clock to find resources and also allows the user to express themselves in seconds instead of blocks which I believe is much more friendly and reliable when looking up a resource. This allows for example to have resources that will resolve *exactly* at a specified time.

This does not mean MRUs will not have connections with the blockchain. A proposal the other day talking with @zelig, was to include the block hash as a header field in an update operation, so it can be proven the update didn't exist prior to that block, and verify that updates are in order.
