### ISSUE TITLE
Move swarm to its own repository.

### ISSUE THREAD

**Issue by cobordism** [ethersphere/swarm#530]
We just had a talk at the Orange Summit about how swarm's repos are confusing. Why is it in the dame repository as geth? ... except that it isn't because it is in a fork of that repo... It's confusing.

This issue is to propose the creation of an ethereum/swarm repository to hold the swarm source code, swarm issues, swarm wiki and swarm PRs all in one place.
release branches, master branch for dev, Tags for specific versions. Feature branches for testing. All in one place.

The current setup is convoluted and we know it - we are after all preparing to push to master upstream... and we use ethersphere for our issues precisely to seperate the from geth issues... but maybe it would be even better if it didn't have to be a geth repo at all...

**Comment by nonsense** [comment]
Swarm code has not been integrated to `ethereum/go-ethereum/master` repo/branch for many months now. Currently we have a consolidated branch of the most up-to-date Swarm code at `ethersphere/go-ethereum/swarm-network-rewrite` repo/branch.

It is our highest priority to merge `ethersphere/go-ethereum/swarm-network-rewrite` to `ethereum/go-ethereum/master` and sync with the codebase we have been part of since the beginning.

There are a few blockers among other issues, which are the reason why we are not doing the merge right now:
1. Backward-incompatible changes to the Swarm hashing algorithm - if we merge today, everyone’s ENS hashes would have to change.
2. Lack of Multihash support.
3. etc.

Once these issues are resolved, and we merge upstream, we can consider moving Swarm to it’s own repository. However I think we must first have a stable Swarm branch at `ethereum/go-ethereum/master` as it should have been all along.

I think it would be very unwise to do a split of the codebase into its own repo before we merge upstream.

I am not convinced we should do that even after we merge upstream.

I think we should do a better job at having the main entrypoint to the Swarm project on `ethereum/go-ethereum/master` branch within the `swarm` subfolder as a start.

**Comment by JohnnySheffield** [comment]
My main issue with having swarm coupled with a nom relevant codebase is mixing two things that do completely different things - swarm is a distributed file storage with incentive layer, ethereum is a smart contract platform (maximally simplified) - if they are tightly coupled, we should consider geth an upstream and define update cycles, if they are not i think it is reasonable to explore possibilities for spearating the concerns.

I honestly don’t mind any solution - as long it is clear for newcoming devs where to start and how to build, and i lack inside knowledge to provide technical proposals how to continue with the current codebase,

But i know that there should be a repo that is clearly focused on swarm, as swarm is one of the tree pillars for the distributed web and requires focus on its own.

**Comment by holisticode** [comment]
There is no reason to rush ahead and do a split right away because someone complained during the summit, even if their arguments were all unconditionally valid. I do agree to @nonsense 's evaluation of the **current** situation and priorities.

However I do believe that after having resolved the `swarm-network-rewrite` merge to `master`, an actual split is something to consider. Arguments being:
* Clear separation of projects for the community
* Independence in merge cycles and merge moments (no third "party" approval and delays thereof)
* Independence in repo management decisions
* Individual issue management and tracking, no need for the `ethersphere` repo, which de facto **does** introduce a split in the code base. Think of how a user perceives this split, not how convenient it is to us
* Simplified workflow for us (no need for "don't merge" PRs, only PRs to `master`)

Having said that, I am also not fully convinced that a split is the best solution. Just wanting to document arguments to do so.

**Comment by lmars** [comment]
The Swarm team has been working in a separate repository for a while now (i.e. the very one we are currently discussing on), and it has really helped in a lot of ways. All issues / pull requests are about Swarm, the team has control of the repository, can decide when to merge, can have their own Travis setup etc.

I agree that the current focus should be on merging `swarm-network-rewrite` into `master` and making it the official release, but I think moving back to `ethereum/go-ethereum` rather than keeping day to day development in a separate repository will bring back some of the issues we solved by using this repository instead.

Perhaps we just deprecate the `ethereum/go-ethereum/swarm` directory and point it to master of `ethereum/swarm` as part of us finally releasing POC3?

**Comment by acud** [comment]
I am generally leaning towards keeping it in the main ethereum repo.

The reality is that we have dependencies on the go ethereum codebase. Using git modules is an option but does not necessarily solve the problem of dereferencing. 

We would have to by synced on 2 repositories simultaneously in order work normally, plus the complexity of working in a nested repository. Breaking changes in the geth repo might not manifest locally immediately as of such.

Plus, unless we introduce vendoring of the geth dependencies, you would still be forced to work in the swamp of `go-ethereum/swarm` - you would not be able to clone just the swarm repository, compile and run (AFAIK). Even if you'd pull out to a sister repository that would sit side by side with the main repo - you'd still need to run constant fetches 

Working within the main repo, although might not be so comfortable, has reasonable solutions (namespacing issues and PRs, working with filters on issues and PRs). If we really want to - we could also set up our own public issue tracker

I think that the benefit of working in the main repo would benefit greatly for widespread adoption, and the evidence to that is that people come to the swarm summit and use their time to give us a hard time for our documentation and community management. Its actually a good sign. And surely we could do more in that realm, and prevent many misunderstandings.

Edit: having said that - I also think that the current setup, having our own travis setup - works pretty well. Long lived branches should not really happen and we should iterate faster with merges to `master`, and to reiterate on what @holisticode said - we shouldn't get rushed into a panic of making changes just because someone complained (but if we do make changes, i'd side with residing in the main repo)

**Comment by JohnnySheffield** [comment]
Hurrying with this kind of decisions is currently more risky than keeping status quo - my position is on a more careful side, but i felt the need to open up this topic on my SOS talk as i haven’t seen any discussion on this.

That said - i think there is legitimate need for a separate repo.

Protocol strength is in number of teams and implementations working on it. 

How does one implement swarm protocol in javascript (or pascal or whatever)? Does that person also builds on top of geth?

And i do believe it is important to implement swarm in more than one language. With only one implementation we’re kinda stuck for the future.

Shouldn’t swarm be ethereum client agnostic? 

Today geth tommorow beth, clients will change but the protocol won’t (hopefully)

Most important thing for widespread swarm adoption is clean and readable spec of the protocol that can be implemented in arbitrally picked language and as part of any repo and project, keeping it coupled with main repo will only make it less visible, harder to read and maintain.


I honestly believe it is not the question will swarm be a separate repo - it most definetly will. The question is will current (core team) implementation of swarm protocol will be maintained as a separate repo. 

The moment you get a second implementation of the protocol in different language by a different team it will be most probably ethereum client agnostic, and separated as a specific repo as that team will not carry any technical debt when starting on their swarm protocol implementation.

**Comment by lmars** [comment]
@justelad 

> The reality is that we have dependencies on the go ethereum codebase. Using git modules is an option but does not necessarily solve the problem of dereferencing.

I don't think having dependencies on a codebase is a good reason for the code to be part of that codebase, in fact by saying Swarm "has dependencies on" rather than being "part of" the go-ethereum codebase really points to the fact Swarm should just be a separate thing with go-ethereum vendored in (just like we [vendor all other dependencies](https://github.com/ethersphere/go-ethereum/blob/swarm-network-rewrite/vendor/vendor.json)).

We have been using a separate repository for a while now, and it's working quite well. Officially switching to `ethereum/swarm` would just mean we would `govendor update` go-ethereum every now and then (probably on each geth point release) rather than our current `git rebase upstream/master`.

I also think a separate repository would help to raise the profile of Swarm in general, the go to place to see the code, issues, wiki, docs, links etc., which is very important for the wider community.

**Comment by holisticode** [comment]
I would only like to add to the discussion that personally I am not fond of the argument that being part of `go-ethereum` is needed to get visibility. Our product should speak for itself. If its quality will reach the desired maturity it will naturally attract visibility and it will be perceived as part of the stack nonetheless. I'd prefer own merits to be the selling point rather than being promoted. Very personal opinion which might be short-sighted.

**Comment by dleonard00** [comment]
From my experience and from what I understood from Nikola Jokic's presentation this 👇 below is  problem we are working to solve. 
> The current setup is convoluted and we know it

Moving Swarm to it's own repository is an obvious proposed consideration, because this is how many other open source projects are structured and thus may provide some amount of orientation for new users. But, the location and relationship of swarm with respect to ethereum/go-ethereum is an attempt to solve that problem, but is not the problem itself.

Let's consider leaving the project structure exactly as it is (since we are at consensus that this must wait), and implement what @nonsense proposed above:

> I think we should do a better job at having the main entrypoint to the Swarm project on ethereum/go-ethereum/master branch within the swarm subfolder as a start.

I will begin by creating a pull request for a readme at the root of [etherspehere/go-ethereum/swarm-network-rewrite/swarm](https://github.com/ethersphere/go-ethereum/tree/swarm-network-rewrite/swarm)

**Comment by cobordism** [comment]
The decision is not to move Swarm to its own repo at the moment.

However we have consolidated all Swarm code at the master branch
https://github.com/ethereum/go-ethereum/tree/master/swarm
and we have a central point of entry in the readme: https://github.com/ethereum/go-ethereum/blob/master/swarm/README.md

The release process has also been cleaned up as a result of this discussion as has the Swarm development workflow.

I will close this issue for the time being. We may revisit this discussion in the future.
