### ISSUE TITLE
improve error message: Manifest entry for X not found

### ISSUE THREAD

**Issue by cobordism** [ethersphere/swarm#726]
Example:
When a request is made to bzz://somesite.eth/ and a swarm manifest is found at somesite.eth, but it does not contain a default entry, then we show the error "Manifest entry for ' ' not found"

I think that "Manifest entry for 'XYZ ' not found" / "Manifest entry for ' ' not found" is a very cryptic error message. 

I'd like to see something like "The loaded manifest does not contain an entry for XYZ" / "The loaded manifest does not contain a default entry", together with a clickable link to the same manifest with the bzz-list scheme.

**Comment by cobordism** [comment]
c.f. https://github.com/ethersphere/go-ethereum/issues/156

**Comment by acud** [comment]
> I think that "Manifest entry for 'XYZ ' not found" / "Manifest entry for ' ' not found" is a very cryptic error message.

I have changed the aforementioned error to: `fmt.Errorf("Not found: could not find resource '%s'", path)`. I think that mentioning manifests in general is cryptic and does not give extra information, since a `not found` can be either an `entry not found` but also `network could not find since it doesn't exist` - the two should be merged into one error message.

> I'd like to see something like "The loaded manifest does not contain an entry for XYZ" / "The loaded manifest does not contain a default entry", together with a clickable link to the same manifest with the bzz-list scheme.

this is no longer relevant since we will already fall back to bzz list on http get of a manifest without a default entry.

**Comment by cobordism** [comment]
ok. I see. makes sense.

so if manifest does not have default, and I request manifest, we do bzz-list. But what do we do if I request manifest/abc but the manifest does not contain an abc entry? do we also bzz-list?

**Comment by acud** [comment]
404
