### ISSUE TITLE
P2p handshakes happening despite --maxpeers 0 cli flag

### ISSUE THREAD

**Issue by cobordism** [ethersphere/swarm#864]
Expected behaviour:

When we set `--maxpeers 0` we expect the Swarm node to be "in singleton mode". Specifically we expect there to be no handshakes with other peers.
See also:
https://swarm-guide.readthedocs.io/en/latest/gettingstarted.html#swarm-in-singleton-mode-no-peers

Actual behaviour:
Even with `--maxpeers 0` the node still engages in handshakes.

**Comment by petyaracz** [comment]
It looks like now I can't *drop* peers with admin.removePeer either.

**Comment by nonsense** [comment]
@homotopycolimit @zelig this is expected behaviour. `maxpeers` is not intuitive and does NOT mean that you will have 0 peers. It is just used for limiting inbound connections.

If you want to have a node running in singleton mode, probably best to use `netrestrict` option.

I am closing this, please open if you disagree or if you think this is a bug we should address.

**Comment by cobordism** [comment]
I'm ok with using netrestrict. do the docs reflect this? and do the docs explain maxpeers correctly?

**Comment by nonsense** [comment]
@homotopycolimit I haven't seen a good explanation of `maxpeers`, so I think the docs are wrong. It also depends on the `DialRatio` which can only be set in a `toml` config, and we have no config for in command line arguments.

**Comment by petyaracz** [comment]
I removed maxpeers from the latest version of docs. This version tells you how to run a singleton node. (The version hasn't moved to readthedocs yet)
