### ISSUE TITLE
swarm-smoke tests on internal env slows down after a while

### ISSUE THREAD

**Issue by gbalint** [ethersphere/swarm#934]
If we run the cluster and upload 100s of MBs if files, after a while running the smoke tests takes more and more time.
We are not sure yet if it is a database issue or it is about the uptime of the nodes.

**Comment by nonsense** [comment]
There are a few related issues that cause this to happen, all somewhat unrelated and can be addressed independently:

1. Sometimes chunk requests (retrieve requests) result in timeouts - it is not clear why this is happening in our internal environments, and we need to understand it better:

![screen shot 2019-03-08 at 16 24 55](https://user-images.githubusercontent.com/50459/54037561-bbb05d00-41be-11e9-9be6-3dcd0f514ca8.png)

In a stable private deployment on Kubernetes, we are not supposed to ever see timeouts in `stream.send.request` spans (which belongs to `netstore.fetcher` span) those visible in the screenshot, so we should debug this an understand why it happens.

2. Swarm makes sequential requests for chunks from peers. This means that if a given peer is unstable and doesn't return chunks, all requests to it would timeout, essentially delaying a `GET` request with `N` multiples of `defaultSearchTimeout = 1 * time.Second`. Considering that chunks are 4kb right now, and that we sequentially read buffers of size 128kb, this can easily result in high values of `N`.

A solution would be to issue concurrently `M` requests for chunks (where `M` is let's say 3-5) and cancel the requests as soon as the first response for a chunk is received.

![Screen Shot 2019-03-09 at 00 55 59](https://user-images.githubusercontent.com/50459/54062423-2769e880-4206-11e9-8c36-449f6d8c5caa.png)

3. Swarm makes sequential reads for buffers of size 128kb.

![screen shot 2019-03-08 at 16 33 04](https://user-images.githubusercontent.com/50459/54038042-e0f19b00-41bf-11e9-83a8-e7f0be669df0.png)

Each `lcr.read (LazyChunkReader.Read)` in the screenshot is a buffer of 128kb. This means that for a file of size `X` megabytes, we incur the `X / 128kb` times the latency for the slowest retrieve requests within a given buffer, while we serve the requested content to the client. We should implement some kind of `look ahead` functionality to fetch at least a few buffers (`buffer[n+1]`, `buffer[n+2]`, ... , `buffer[n+m]`) to the local node, while we are serving `buffer[n]` to our client, so that we overlap the latency of the Swarm network with the latency to our client, rather than add them together.

**Comment by cobordism** [comment]
> A solution would be to issue concurrently M requests for chunks (where M is let's say 3-5) and cancel the requests as soon as the first response for a chunk is received.

This seems to allow for griefing attacks.
If I want a particular chunk to be spread more widely in the swarm, I request a chunk from many peers and then cancel all those requests. That way you never pay the Swap fee.... however, your initial requests could well have triggered retrieval requests downstream and the last node to receive the chunk prior to the cancellation will be stuck with the fees.

**Comment by nonsense** [comment]
@homotopycolimit this makes sense.

However currently we don't have any fees. Also the problem you describe is valid even when M=1 - you issue a request and cancel it, leaving nodes downstream to pay the Swap fee. I am not sure how increasing M to 2-3-5 would create an issue... anyone is free to modify the code of Swarm the way they want, so this issue needs to be accounted for on protocol level I think.

**Comment by zelig** [comment]
guys we do pay for requests as well

**Comment by nonsense** [comment]
@zelig could you be a bit more explicit in your comment? The way I understand your comment, payment should happen at the time of the request, not at the time of the delivery, meaning that @homotopycolimit's case is not possible.

It would however mean that 3 requests would be more expensive than 1 request, although I'd argue that >1 number of requests per chunk should be the baseline for Swarm, otherwise the QoS would suffer as we have seen. Maybe an option to reduce M should exist at some point (when we introduce those fees) if you are happy with waiting for so long for your chunks.

**Comment by zelig** [comment]
@nonsense https://github.com/ethereum/go-ethereum/blob/master/swarm/network/stream/stream.go#L863 
i think multiple requests are worth experimenting with later on. At the moment we should find the bug that raised this issue instead.
Dont forget abuot erasure coding also.
