### ISSUE TITLE
Turn off local store validity checks

### ISSUE THREAD

**Issue by adamschmideg** [ethersphere/swarm#997]
A local store always performs validity checks which would fail if we store everything in a global store. To use a local store for mocking, we need to be able to turn off the validity checks.

**Comment by nonsense** [comment]
@adamschmideg what does that mean? Why do this? Can you add a bit more information to tickets, please.

**Comment by holisticode** [comment]
The intention is to reduce the bandwidth needed for tests, as in simulations the nodes would not have to exchange the data of chunks (which is irrelevant for many tests) but only their hashes, in order to validate that syncing and retrieval is working properly.

This should make it possible to allow for bigger (more nodes) and more complex simulations.

**Comment by holisticode** [comment]
There is no need to explicitly turn off validity checks; we can just provide an empty set of validators
